import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased size-full`}
      >
        <header className="w-full flex justify-center">
          <div className="flex gap-2 text-2xl">
            <Link href="/" className="hover:underline">
              Clock
            </Link>
            <Link href="/input" className="hover:underline">
              Input
            </Link>
          </div>
        </header>
        <div className="py-6" />
        <main className=" flex flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
