import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <header className="w-full flex justify-center py-6">
            <div className="flex gap-2 text-2xl">
              <Link href="/" className="hover:underline">
                Clock
              </Link>
              <Link href="/input" className="hover:underline">
                Input
              </Link>
              <Link href="/auth" className="hover:underline">
                Auth
              </Link>
            </div>
          </header>
          <main className="flex-1 flex flex-col items-center justify-center">
            {children}
          </main>
          <footer className="w-full flex justify-center py-6">
            <Link
              href="https://github.com/ethanniser/hydration-test"
              className="hover:underline"
            >
              Source
            </Link>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
